# Generated by Django 4.0.3 on 2022-05-04 01:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_alter_articlecolumn_column_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 1, 55, 16, 96881, tzinfo=utc)),
        ),
    ]
