# Generated by Django 4.0.3 on 2022-05-04 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlepost_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='article_tag',
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='users_like',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 5, 34, 57, 89962, tzinfo=utc)),
        ),
    ]
