# Generated by Django 4.0.3 on 2022-05-04 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_articlepost_article_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 5, 55, 36, 949384, tzinfo=utc)),
        ),
    ]
